### ISSUE TITLE
PHP 7.4 GD install error

### ISSUE THREAD

**Issue by Demoli** [Skywire/skywire-docker#19]
On PHP 7.4 the GD installation process is different.

Line skywire-docker/php-fpm/Dockerfile:31
`&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/\`

Should be replaced with

`&& docker-php-ext-configure gd --with-freetype --with-jpeg \`

only for PHP >=7.4

**Comment by valguss** [comment]
Now updated and merged
